### ISSUE TITLE
Specify minimum versions of Python and Django

### ISSUE THREAD

**Issue by DmytroLitvinov** [guettli/django-check-html-middleware#1]
We need to specify that the minimum supported version for Python is `3.6` (I saw it uses type hints `List`) and about Django I am not sure.

**Comment by guettli** [comment]
It would be great if could provide a pull-request.

**Comment by DmytroLitvinov** [comment]
Sure, I can but as I said in the description of issue, I don't know the minimum supported version of Django.

**Comment by guettli** [comment]
@DmytroLitvinov me, too. I haven't tried older versions up to now.

**Comment by DmytroLitvinov** [comment]
@guettli ,
Prepared PR https://github.com/guettli/django-check-html-middleware/pull/2 for that
